<a href="https://colab.research.google.com/github/ZohrehFeridoun/RL_ex5/blob/main/RL5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install gym

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np
import gym
import time
from IPython.display import clear_output
import random

env=gym.make("FrozenLake8x8-v1")

In [ ]:
import copy

columns_size = env.action_space.n
rows_size = env.observation_space.n

q_table = np.zeros((rows_size , columns_size))
q_table_copy = copy.deepcopy(q_table)

print(q_table_copy)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Define hyperparameters
num_episodes = 10000
max_steps_per_episode = 100
learning_rate = 0.1
discount_rate = 0.99
exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001
epsilon_min = 0.05

# Train the agent
for episode in range(num_episodes):
    state = env.reset()
    done = False
    step = 0

    while not done and step < max_steps_per_episode:
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        # Take new action
        new_state, reward, done, info = env.step(action)

        # Update Q-table
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        # Update state and step
        state = new_state
        step += 1

    # Decay exploration rate
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

In [ ]:
# Initialize variables to track rewards
rewards_all_episodes = []

# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset() # reset for each new episode
    done = False # keep track whether or not the episode finishes, start=False
    rewards_current_episode = 0 # track reward, start=0

    # Loop for each step in the episode
    for step in range(max_steps_per_episode):
        # Exploration & exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1) # create random number (r) at each time step
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action) # apply action & get results

        # Update Q-table
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        state = new_state
        rewards_current_episode += reward

        if done:
            break

    # Decay exploration rate
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)

    rewards_all_episodes.append(rewards_current_episode)

In [ ]:
# Calculate and print average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print("Average reward per thousand episodes\n")
for r in rewards_per_thousand_episodes:
    print(count, ':', str(sum(r/1000)))
    count += 1000

# Print updated Q table
print('\n\nQ-table\n')
print(q_table)

Average reward per thousand episodes

1000 : 0.025000000000000015
2000 : 0.17000000000000012
3000 : 0.33600000000000024
4000 : 0.4940000000000004
5000 : 0.5100000000000003
6000 : 0.5410000000000004
7000 : 0.5040000000000003
8000 : 0.5570000000000004
9000 : 0.5220000000000004
10000 : 0.5510000000000004


Q-table

[[3.69451484e-01 3.69223794e-01 3.73492212e-01 3.69383953e-01]
 [3.77004356e-01 3.76861965e-01 3.77343563e-01 3.94221202e-01]
 [3.96450335e-01 3.97930546e-01 4.13049420e-01 3.97435704e-01]
 [4.15882285e-01 4.16192917e-01 4.29047371e-01 4.16176964e-01]
 [4.40315218e-01 4.40484135e-01 4.63132252e-01 4.41553321e-01]
 [4.64299202e-01 4.66436861e-01 4.89043655e-01 4.66569288e-01]
 [4.79181007e-01 4.80957087e-01 5.05094998e-01 4.86521758e-01]
 [4.86240379e-01 5.08967564e-01 4.90861810e-01 4.85651870e-01]
 [3.66803535e-01 3.66844976e-01 3.66965619e-01 3.72911348e-01]
 [3.73131722e-01 3.73688264e-01 3.82989708e-01 3.73809099e-01]
 [3.82204794e-01 3.83919677e-01 3.84172787e-01 3.9899903

In [ ]:
# See the agent actually play
for episode in range(3):
    state = env.reset()
    done = False
    print("Episode", episode+1, "\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):
        clear_output(wait=True) # clear output for another output printout,for visual smoothness
        print(env.render(mode="ansi")) # see where agent is on the grid
        time.sleep(0.3)

        action = np.argmax(q_table[state, :])
        new_state, reward, done, info = env.step(action)

        if done:
            clear_output(wait=True)
            print(env.render(mode="ansi"))
            if reward == 1:
                print('Win')
                time.sleep(3)
            else:
                print('Fell hole')
                time.sleep(3)
            clear_output(wait=True)
            break

        state = new_state # if  the last action do not complete the episode, then skip the conditional, move to new state &  next time step

env.close() # close the environment

  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG

Win
